spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/pet_foster_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
<<<<<<< HEAD
    password: dyk2005dyk
=======
    password: wyy1173231
>>>>>>> eca9c944a480341c8d84a8e6ab9e97d337a8f62a
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Spring Security 配置
  security:
    user:
      name: root
      password: 123456
<<<<<<< HEAD
=======

>>>>>>> eca9c944a480341c8d84a8e6ab9e97d337a8f62a
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.petfoster.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 服务器 & 编码配置（正确路径，无警告）
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true